apiVersion: v1
kind: ConfigMap
metadata:
  name: product-api-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product-api.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.aspnetEnvironment | quote }}
  ASPNETCORE_URLS: "http://+:8080"
  Kafka__BootstrapServers: {{ .Values.config.kafka.bootstrapServers | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.config.otel.endpoint | quote }}
