apiVersion: v1
kind: Secret
metadata:
  name: product-api-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__Postgres: "Host={{ .Values.config.db.host }};Port={{ .Values.config.db.port }};Database={{ .Values.config.db.name }};Username={{ .Values.secrets.dbUser }};Password={{ .Values.secrets.dbPassword }}"
  Redis__ConnectionString: "{{ .Values.config.redis.host }}:{{ .Values.config.redis.port }},password={{ .Values.secrets.redisPassword }}"
  Kafka__Username: {{ .Values.secrets.kafkaUser | quote }}
  Kafka__Password: {{ .Values.secrets.kafkaPassword | quote }}
  {{- if .Values.secrets.jwtPrivateKeyPem }}
  Jwt__PrivateKeyPem: {{ .Values.secrets.jwtPrivateKeyPem | quote }}
  {{- end }}
