apiVersion: v1
kind: Service
metadata:
  name: product-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "product-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
