{
 "title": "Product API",
 "refresh": "30s",
 "panels": [
  {
   "title": "Request Rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"product-api\"}[1m]))",
     "legendFormat": "req/s"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"product-api\",code=~\"5..\"}[1m])) / sum(rate(http_request_duration_seconds_count{job=\"product-api\"}[1m])) * 100",
     "legendFormat": "error %"
    }
   ]
  },
  {
   "title": "p95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"product-api\"}[5m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Process Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"product-api\"}",
     "legendFormat": "uptime"
    }
   ]
  }
 ]
}